fix

diff --git a/.github/workflows/all-in-one.yaml b/.github/workflows/all-in-one.yaml
--- a/.github/workflows/all-in-one.yaml
+++ b/.github/workflows/all-in-one.yaml
@@ -16,15 +16,6 @@ jobs:
         os: [ubuntu-latest, windows-latest]
         build_type: [Release]
         cpp_compiler: [g++, clang++, cl]
-        include:
-          - os: windows-latest
-            cpp_compiler: cl
-          - os: windows-latest
-            cpp_compiler: clang++
-          - os: ubuntu-latest
-            cpp_compiler: g++
-          - os: ubuntu-latest
-            cpp_compiler: clang++
         exclude:
           - os: ubuntu-latest
             cpp_compiler: cl      
@@ -66,7 +57,11 @@ jobs:
     - name: Run Test (Windows)
       if: runner.os == 'Windows'
       working-directory: ${{ steps.strings.outputs.build-output-dir }}
-      run: .\AllInOne.exe
+      run: |
+        if (-Not (Test-Path .\AllInOne.exe)) {
+          Write-Error "Test executable not found!"
+        }
+        .\AllInOne.exe || exit 1
 
     - name: Run Test (Linux)
       if: runner.os == 'Linux'
